# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-03-19 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='lrp',
            field=models.CharField(max_length=50),
        ),
    ]
