# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-03-15 01:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeid', models.CharField(max_length=10)),
                ('typename', models.CharField(max_length=100)),
                ('childtypenames', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'mml_types',
            },
        ),
    ]
