# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-03-15 06:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_goods'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='fatherid',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
