# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-03-19 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190319_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='old',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='sex',
            field=models.CharField(default='', max_length=10),
        ),
    ]
