# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-03-15 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_goods_fatherid'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('freindword', models.CharField(default='', max_length=30)),
            ],
            options={
                'db_table': 'mml_user',
            },
        ),
    ]
