# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-03-16 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_order_ordergoods'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordergoods',
            name='total',
            field=models.FloatField(default=0),
        ),
    ]
